# Generated by Django 4.1.4 on 2022-12-07 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filial1', '0003_alter_client_card_number_remove_order_ingridient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='orders',
            field=models.ManyToManyField(related_name='food', through='filial1.Order', to='filial1.ingridient'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='ingridient',
        ),
        migrations.AddField(
            model_name='order',
            name='ingridient',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='filial1.ingridient'),
            preserve_default=False,
        ),
    ]
